# Generated by Django 4.2.6 on 2023-10-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_luancarminatti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
