# Generated by Django 4.2.6 on 2023-10-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_luancarminatti', '0002_alter_project_date_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
