# Generated by Django 4.2.6 on 2023-10-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_luancarminatti', '0005_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/images/'),
        ),
    ]
